prompts:
  - an Ian with a Dog
  - an Ian with a beard
  - an Ian with a baby and a pineapple

providers:
  - id: replicate:black-forest-labs/flux-schnell
    config:
      go_fast: true
      megapixels: '1'
      num_outputs: 1
      aspect_ratio: '1:1'
      output_format: 'webp'
      output_quality: 80
      num_inference_steps: 4
